name: typing

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pyright:
    name: Check type annotations with pyright
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]
      - name: Check types with pyright
        uses: jakebailey/pyright-action@v2
        with:
          version: 1.1.411
